### ISSUE TITLE
IndexOutOfRangeException parse crash

### ISSUE THREAD

**Issue by TerrahKitsune** [swiftyspiffy/TwitchLib#190] opened 2017-05-10 17:06 UTC
Row 49 in Models/Client/WhisperMessage.cs will split with tail on the raw irc which will result in an unhandled IndexOutOfRageException if the tail contains a semi-colon.

**Comment by swiftyspiffy** [comment] 2017-05-10 21:04
Looking into this now.

**Comment by swiftyspiffy** [comment] 2017-05-10 21:24
Git auto closed the issue, but feel free to reopen if the problem is not fixed with the above commit.

**Closed** 2017-05-10 21:24 UTC
