### ISSUE TITLE
401 Unauthorized server reply with TwitchApi.UpdateStreamTitleAndGame

### ISSUE THREAD

**Issue by jscoys** [swiftyspiffy/TwitchLib#78] opened 2016-10-31 12:48 UTC
Hi,

I'm getting a 401 error. I verified my infos, all is good, game name, status, channel name...

Maybe I'm using badly the oAuth key? I tried with the oAuth:, without, it doesn't work for me. What i'm doing wrong?

private async void button9_Click(object sender, EventArgs e)
        {
            await TwitchApi.UpdateStreamTitleAndGame(this.textBox5.Text, this.comboBox2.SelectedItem.ToString(), this.textBox1.Text, "oauth:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
        }

**Comment by igor523** [comment] 2016-10-31 17:53
Check your scopes! Not any oauth can be used with this, you'll have to request token with specific scopes - check Twitch API documentation for that

**Comment by swiftyspiffy** [comment] 2016-10-31 19:35
Igor is correct. Check the scope that was used to create your token. Ensure you don't have typos in your OAuth and username. The "oauth:" shouldn't matter.

**Comment by jscoys** [comment] 2016-11-01 15:34
Hi thx for your replies. Sorry i'm newbie here, how to do that?

**Comment by developerlegion** [comment] 2016-11-02 04:20
I am also having this issue only, in my case, my scopes are correct and I get a 403 forbidden error instead. Any ideas

**Comment by swiftyspiffy** [comment] 2016-11-02 04:31
Two claims to this issue, I'll look into it now.

**Comment by swiftyspiffy** [comment] 2016-11-02 04:35
I was able to use the Modify Channel Status/Game box on the example application using my own channel username and oauth (with all scopes).

Try using the example application.

**Comment by developerlegion** [comment] 2016-11-02 13:15
I am using the latest Github. I originally tried it with all scopes, then changed it to only a selected sum, which included the one required to change the title. I was looking at the sample code when I initially did mine. When I went through the process of getting the token, their documentation talked about state being one of the parameters. I didn't include that in both the user(my botchannel) request and the secondary request to get the token itself. Im not sure if that is the issue or not. If your library has a way to obtain the token, I didn't use it. I did it through a browser and postman

**Comment by swiftyspiffy** [comment] 2016-11-02 19:49
To the best of my knowledge, it is not possible to generate the oauth token. I too tested the example application using all scopes and it worked. You didn't mention if all scopes worked and not using all scopes didn't work? I'll test later with only the specific scope that should be needed to modify the game/status.

**Comment by developerlegion** [comment] 2016-11-02 22:19
I tested with both and got the same response. I am going to look into this further myself as mine is an access denied 403, so something is off. When I got my token, I got the access token and refresh token along with the scope in the return payload.

**Comment by developerlegion** [comment] 2016-11-03 03:16
I didnt use the implicit flow. I used the first one, so that could be it. I am going to try the implicit version and see if that works.

**Comment by swiftyspiffy** [comment] 2016-11-03 03:19
If you trust me, you can use what I use to test it. This is the site of the streamer I develop for. I've uploaded a script to generate the client id and oauth token for all scopes: https://burkeblack.tv/testapp/twitchauth.php

**Comment by developerlegion** [comment] 2016-11-03 03:30
While I won't actually authorize.. the url tells me that I used the correct technique the first time that I set mine up... so not sure why I am getting 403 forbidden. Gotta be something else then.

**Comment by swiftyspiffy** [comment] 2016-11-03 03:33
You might try creating a dummy account and using the above link to authorize  just to see if the issue is rooted deeper than the authorization, or if there is something funny going on with your authorization.. I've tested several times today using that link to generate oauth.

**Comment by developerlegion** [comment] 2016-11-03 03:34
I am actually using my secondary bot account to test.. I am going to run through it one more time and double check everything... I think that part is fine, its the second part that gets me the token that might be wrong.

**Comment by swiftyspiffy** [comment] 2016-11-03 03:35
If you're interested, the code that link above uses is right here: https://github.com/Xxplosions/twitchtv-oauth

**Comment by swiftyspiffy** [comment] 2016-11-03 03:36
And usage in example application:
![Image of Usage](http://swfty.xyz/?id=692zEA296)

**Comment by developerlegion** [comment] 2016-11-03 03:41
The access token I get back does not have oauth: with it.. at least not for that url. I looked at the sample before and from what I understand it should be correct. 

Once I get that code back, I send a second request to get a token. Below is the json that I get back- minus my codes.

{
  "access_token": "mytoken",
  "refresh_token": "myRefreshtoken",
  "scope": [
    "channel_check_subscription",
    "channel_commercial",
    "channel_editor",
    "channel_feed_edit",
    "channel_feed_read",
    "chat_login",
    "user_blocks_edit",
    "user_blocks_read"
  ]
}

**Comment by swiftyspiffy** [comment] 2016-11-03 03:45
The library should tolerate "oauth:" present or not. I've tried both and they both work. Regarding your response data, I'm not 100%. I haven't meddled much in the obtaining of the oauth token, but I linked the php twitch library I use above and the readme includes how it works, which may help you.

Just looking at your response there, it seems correct.

Though this line in the php implementation details:
```
$user_name = $twitchtv->authenticated_user($access_token);
```
makes me think you may need to use the token to generate the oauth code.

**Comment by developerlegion** [comment] 2016-11-03 03:49
According to twitch api docs it is supposed to be 2 url Posts... first one gets the code and the second one gets the token. The implicit version, gets the token instead of the code, so you change code to token. I have tried both and can't for the life of me figure out why I keep getting 403... its really frustrating. 

I will check out this php library that you sent me.. not sure if it will help but I will try. One a side note, I had to generate a new secret when I setup my bot on my account. I don't think that changes the client id or anything does it? I am wondering if that is the issue... not sure.

**Comment by developerlegion** [comment] 2016-11-03 03:50
In your library I get that back calling your UpdateStreamTitleAndGame method.. I haven't tried the other ones yet.

**Comment by swiftyspiffy** [comment] 2016-11-03 03:51
I don't think you'd get a token if your client id was invalid/changed. That being said, I'm going to take the scopes you listed above and give it a go on my side.

**Comment by developerlegion** [comment] 2016-11-03 03:57
I was using the await and async on my method for that call and got the 403, but when I took the await out and async out.. the app doesn't crash, but also doesn't update either... weird Is their a call back for successful updates of title and game?

**Comment by swiftyspiffy** [comment] 2016-11-03 04:01
Yes, returned will be raw json blob of a Channel object. I will make it return a channel object and push that now.

**Comment by developerlegion** [comment] 2016-11-03 04:03
Thanks. I am wondering if the 403 had something to do with me using await and async since it didn't do that when I took it off.. I am still using the nuget version, so not sure if I can test it unless I take out the nuget and do a pull/compile version

**Comment by swiftyspiffy** [comment] 2016-11-03 04:09
Looks like a 403 is a invalid access token, assuming they haven't changed their error code meanings in the last year: https://discuss.dev.twitch.tv/t/solved-keep-getting-a-403-when-editing-channel-info/3914/2

Regarding the update, ya if you are using NuGet you won't be able to get it. That being said, you UpdateStatusAndGame still returns a string which you can use to verify.

**Comment by swiftyspiffy** [comment] 2016-11-03 04:12
As a side note I just updated the library to return a channel object, I know that doesn't really affect you though.

**Comment by developerlegion** [comment] 2016-11-03 04:12
Thanks, I will look into this link.. and I believe that string may be all I needed,

**Comment by developerlegion** [comment] 2016-11-03 04:22
It came back good, but I think I may know what the issue is. I think it auths its own channel and not mine. in the _links section it doesn't list my channel, but lists its channel.... haha but yet has my channel's client id. I must have missed something or got my stuff mixed up.

**Comment by swiftyspiffy** [comment] 2016-11-03 04:23
Client Id is matched to an application, so client id shouldn't matter. Basically the change is being done on part by the application identified by the client id. But ya, if the _links section is not the profile you are trying to change, that might be a problem :)

**Comment by developerlegion** [comment] 2016-11-03 04:29
Looks like that was what it was. For some reason, I choose to try to get this token through my bot account... lesson learned their. It is working now as expected.

**Comment by developerlegion** [comment] 2016-11-03 04:31
I will have to go through this all again when I actually put a login screen in, which will be sometime later. I will probably look into that php thing if its faster.

**Comment by swiftyspiffy** [comment] 2016-11-03 04:36
Awesome! I'll close this for now!

**Closed by swiftyspiffy** 2016-11-03 04:36 UTC
