### ISSUE TITLE
NullReferenceException in Mono after connection

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#154] opened 2017-03-19 01:23 UTC
My code runs properly on my PC, both through Visual Studio and Xamarin Studio. When I run it with Mono on my Ubuntu server, however, I get the below stack trace.

My code:

```csharp
client = new TwitchClient(new ConnectionCredentials(username, oauth), "channelname", logging: true);
TwitchApi.SetClientId(clientId);

client.AddChatCommandIdentifier('!');

client.OnConnected += LogEvents;
client.OnDisconnected += LogEvents;
client.OnConnectionError += LogEvents;
client.OnIncorrectLogin += LogEvents;

client.OnChatCommandReceived += CommandHandler;

client.ChatThrottler = new MessageThrottler(2, new TimeSpan(0, 0, 5));

client.Connect();
```

Output:

```
[TwitchLib] TwitchLib-TwitchClient initialized, assembly version: 1.4.3.32199
[TwitchLib] Connecting to: irc-ws.chat.twitch.tv:80
[TwitchLib] Joining channel: channelname
[TwitchLib] Should be connected!
[TwitchLib] Received: :tmi.twitch.tv 001 botname :Welcome, GLHF!

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at TwitchLib.Internal.Requests.handleWebException (System.Net.WebException e) [0x00000] in <filename unknown>:0
  at TwitchLib.Internal.Requests+<MakeGetRequest>d__0.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.String].GetResult () [0x00000] in <filename unknown>:0
  at TwitchLib.Internal.TwitchApi+<ValidClientId>d__82.MoveNext () [0x00000] in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <filename unknown>:0
  at System.Runtime.CompilerServices.TaskAwaiter`1[System.Boolean].GetResult () [0x00000] in <filename unknown>:0
  at TwitchLib.Internal.TwitchApi+<ValidClientId>d__83.MoveNext () [0x00000] in <filename unknown>:0
```

**Comment by swiftyspiffy** [comment] 2017-03-19 01:51
It looks like the library is trying to validate a client id that you're using and is failing to do so. Are you setting a client id and using a valid client id? The issue doesnt seem to be linked to the client itself but rather TwitchApi.

**Comment by vaindil** [comment] 2017-03-19 01:52
Yes, I printed out the client ID variable and it's valid, it's the same one I use when testing locally.

**Comment by swiftyspiffy** [comment] 2017-03-19 02:02
https://github.com/swiftyspiffy/TwitchLib/blob/f460f8cb9e28bf9f994c0069a7b36239d911ddb7/TwitchLib/Internal/TwitchAPI.cs#L858

Pretty sure it's this request that is failing and not being caught correctly. Perhaps you can set a breakpoint here and see if you see anything interesting. I tried reproducing and it seems to be working.

**Comment by vaindil** [comment] 2017-03-19 03:51
I don't know of a way to debug Mono on an Ubuntu server. I ran an Ubuntu desktop VM and tried running it on that, had no problems. I'm out of ideas.

**Comment by vaindil** [comment] 2017-03-19 04:22
I ended up cloning the library and sticking `Console.WriteLine()` everywhere. Looks like the error is [here](https://github.com/swiftyspiffy/TwitchLib/blob/f460f8cb9e28bf9f994c0069a7b36239d911ddb7/TwitchLib/Internal/Requests.cs#L86)--this cast is failing, so `errorResp` is null.

**Comment by swiftyspiffy** [comment] 2017-03-23 19:38
So as far as I can tell, the only sort-of solution for this is to throw the default webexception instead of attempting to work off the httpstatuscode and getting a nullreference which makes debugging quite difficult.

**Comment by swiftyspiffy** [comment] 2017-03-30 20:18
I think the commit above should lead to the true cause. I'm going to go ahead and close this.

**Closed by swiftyspiffy** 2017-03-30 20:18 UTC
