### ISSUE TITLE
Using multiple SendMessage's after eachother  triggers the last OnMessageSent multiple times

### ISSUE THREAD

**Issue by borgej** [swiftyspiffy/TwitchLib#218] opened 2017-06-20 21:09 UTC
Hi

First of all, thanks for the awesome library!
Im having an issue with the SendMessage() that triggers the OnMessageSent event.

Sending multiple messages after another triggers only the last OnMessageSent event multiple times.
Or Im doing something wrong.

In the example under either the 
`client.SendMessage($"@{chatmessage.DisplayName} is now chilling on the floor and sort of all over the place for a minute!");`
The OnMessageSent event gets sent tree times for this SendMessage, the first two SendMessage() events does not trigger.

If the code enters the else {} clause this OnMessageSent event triggers two times for that SendMessage.

Probably the worst explanation ever, hope you know if I'm doing something wrong or if this is a bug ;)

Example code:
```
var client = GetClient();

client.SendMessage($"@{chatmessage.DisplayName} places the gun to their head!");

Random rnd = new Random(Guid.NewGuid().GetHashCode());

var theNumberIs = rnd.Next(1, 6);

var timeout = new TimeSpan(0, 0, 1, 0);
var message = "Timed out for " + Convert.ToString(timeout.Minutes) + " minutes";

// User dies(timeout) if 1 is drawn
if (theNumberIs == 1)
{
	Wait(1);
	client.SendMessage($"@{chatmessage.DisplayName} pulls the trigger...... brain goes everywhere!! Who knew @{chatmessage.DisplayName} had that much in there?");
	//Timeout user
	var joinedChannel = client.GetJoinedChannel(Channel);
	client.TimeoutUser(joinedChannel, chatmessage.DisplayName, timeout, message);
	client.SendMessage($"@{chatmessage.DisplayName} is now chilling on the floor and sort of all over the place for a minute!");
}
// Gets away with it!
else
{
	Wait(1);
	client.SendMessage($"@{chatmessage.DisplayName} pulls the trigger...... CLICK!....... and survives!!");
}

```

**Comment by swiftyspiffy** [comment] 2017-06-21 00:59
Ya.... this one is tricky lol. So, in case you didn't know, Twitch doesn't actually send confirmation of a sent message when you send a message via TMI or websockets. This event was hacked in because someone wanted the kind of information you'd get with a OnMessageReceived event. All information in the event is pulled from non-sending event areas.

I'll see what I can do as far as fixing this. This event has proven to be a bit of a pain in the ass.

Here's some info:
Event firing happens here: https://github.com/swiftyspiffy/TwitchLib/blob/0cea8b1db2e27ce7d01e2bb94835cb2902f7d4e2/TwitchLib/TwitchClient.cs#L712

Note that this event actually fires when a UserState message is received. Because a UserState is also received when joining a channel, we need to keep track of whether or not we have joined a specific channel, and if we have already, then we can assume it's a SentMessage. This is pretty hacky imo. If you know a better route, I'm all ears.

**Comment by borgej** [comment] 2017-06-21 02:14
Thanks for the reply! 
I'll also take a dive into it and see if I can figure out anything!

**Comment by swiftyspiffy** [comment] 2017-07-01 02:58
Alright, so I ran the test application and sent multiple messages one after another and listened to onMessageSent. I then logged them to textbox and here are the results.

![https://swfty.xyz/139TA2148](https://swfty.xyz/139TA2148)

As far as I can tell, that is correct. Am I missing something?

**Comment by swiftyspiffy** [comment] 2017-07-07 22:05
I'm going to go ahead and close this. If you're able to reproduce still, go ahead and reopen.

**Closed by swiftyspiffy** 2017-07-07 22:05 UTC
Labels: bug, help wanted
