### ISSUE TITLE
Bot disconnects sometimes

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#140] opened 2017-03-05 22:17 UTC
Hey swifty,

is there anyway to get hands on some information why the bot disconnects/losts connection?
Someone that uses my bot has some dcs from the server without a reason(at least there is no one for me), thats why I would like to see why it disconnects.

Regards

**Comment by swiftyspiffy** [comment] 2017-03-05 22:23
I would suggest subscribing to the OnConnectionError event. Right now I see that the event isn't super useful as it only contains the bot username. Give me a second and I'll have it bubble up the exception that occurred, as intended.

**Comment by swiftyspiffy** [comment] 2017-03-05 22:33
So have your application listen to TwitchClient's OnConnectionError event, and when it fires log or show the Error.Message and Error.Exception properties.

**Comment by Syzuna** [comment] 2017-03-05 22:34
Kay thanks will try that :)

**Comment by Syzuna** [comment] 2017-03-05 22:48
the newest commit gives me a compiler error that says (translated from german) : The Typ or Namespace "Image" was not found (Missing using-directive or Assembly reference) (thrown from the v5.cs Class)

**Comment by swiftyspiffy** [comment] 2017-03-05 23:02
Oops I committed something from the other branch by accident. One sec.

**Comment by swiftyspiffy** [comment] 2017-03-05 23:10
Looks like the build cleared Travis, so it should be good.

**Comment by Syzuna** [comment] 2017-03-05 23:12
Will try it in a minute :)

Amazing work with your lib btw 👍

**Comment by Syzuna** [comment] 2017-03-05 23:15
This one compiles fine :)

**Comment by Syzuna** [comment] 2017-03-06 09:18
Ok.. I let the Bot run the whole night and I have many System.Exception inside my debug log and  "System.Net.Sockets.SocketException" in System.dll
"System.IO.IOException" in System.dll
"System.Exception" in TwitchLib.dll

(the connection error message didntevent didnt fire here)

maybe there is a websocket problem?

**Comment by swiftyspiffy** [comment] 2017-03-06 09:40
Does the connection remain active when you hit those exceptions, or does it die at the moment those are hit?

**Comment by Syzuna** [comment] 2017-03-06 10:03
It dies, the Lib then fires the onDisconnect Event and I get the popup I made that the bot has been disconnected

**Comment by Syzuna** [comment] 2017-03-06 10:09
To be more precise it says me Disconnected the next time I try to do something in Chat but I think the connection drops before that already

**Comment by Syzuna** [comment] 2017-03-06 10:39
Its running from a normal home internet like the ankhbot. Will try to figure out why its dying and if I find something will inform you about my findings.

**Comment by swiftyspiffy** [comment] 2017-03-06 10:41
It's possible to have a boolean that can be set and have the library auto-reconnect when it detects a disconnect. Maybe I'll look into that.

**Comment by Syzuna** [comment] 2017-03-06 10:43
I mean my bot isnt meant to run 24/7 like e.g. the Nightbot does but it should be able to stay connected for lets say a 10hrs Gaming Stream

**Comment by swiftyspiffy** [comment] 2017-03-06 10:53
Right, it should stay connected as long as the developer needs it to stay connected. Not sure why the library seems to disconnect for you. Do you have other code that uses twitch websockets that can maintain connections on your home internet?

**Comment by Syzuna** [comment] 2017-03-06 10:57
Unfortunately I dont have some other Twitch Code around atm. Will try some things and maybe will try a long running test with the example app also. Maybe I have a bug in my code. who knows

**Comment by Syzuna** [comment] 2017-03-06 11:11
Will try to do some traffic analyzing with wireshark maybe I will find something there

**Comment by swiftyspiffy** [comment] 2017-03-06 11:15
Awesome, keep me updated :)

**Comment by Syzuna** [comment] 2017-03-06 11:28
do you know the IP of the Twitch IRC server? :D

**Comment by Syzuna** [comment] 2017-03-06 19:03
hmm ok wasnt able to reproduce it yet while tracing all packages.. but what I changed in the mean time was to rereference the websocket-sharp.dll into my project which reference was gone for some reason

**Comment by swiftyspiffy** [comment] 2017-03-09 20:05
Yea, if websocketsharp isn't referenced, the library will have a really hard time connecting to twitch web sockets :) . Any update on this, though?

**Comment by Syzuna** [comment] 2017-03-10 01:39
Wasnt able to reproduce the error after that day.. maybe it only was a twitch problem.. 

I think you can close this for now because I didnt find any new tracks why it had this problems.. maybe it rly was all down to that damaged websocketsharp reference

**Comment by Syzuna** [comment] 2017-03-10 01:46
The only thing I noticed while testing stuff was that the lib cant connect if you use win7 it just gives you a plattform not supported error because of the websocket connections although I thought websocket-sharp should support win7 while the System.Net.Websocket does not

**Comment by swiftyspiffy** [comment] 2017-03-10 01:58
That is an interesting error. I was not aware websocketsharp doesnt work on Win7. That's kind of problematic. I'll investigate that a bit I'll close this for the time being though.

**Closed by swiftyspiffy** 2017-03-10 01:58 UTC

**Comment by Syzuna** [comment] 2017-03-10 03:27
well it should support win7 but I still got that error while trying to do a long term test over night on my laptop which only has win7 installed
