### ISSUE TITLE
WebSocketException after Connect()

### ISSUE THREAD

**Issue by phxvyper** [swiftyspiffy/TwitchLib#203] opened 2017-05-29 21:46 UTC
I'm receiving the following error in VS's Output window during debugging:

```
5/29/2017 14:38:06|Fatal|WebSocket.<startReceiving>b__175_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                            at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                            at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                            at WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)
```

The code I'm using to connect with:

```cs
Config = JsonConvert.DeserializeObject<ConfigFile>(File.ReadAllText(ConfigPath));

Client = new TwitchClient(
	new ConnectionCredentials(Config.Username, Config.OAuthToken),
	Config.DefaultChannels?[0] ?? DefaultChannel
);

Client.OnReSubscriber += Client_OnReSubscriber;
Client.OnNewSubscriber += Client_OnNewSubscriber;
Client.OnChatCommandReceived += Client_OnChatCommandReceived;
Client.OnMessageReceived += Client_OnMessageReceived;
Client.OnJoinedChannel += Client_OnJoinedChannel;
Client.OnConnected += Client_OnConnected;
Client.OnConnectionError += Client_OnConnectionError;

Client.Connect();
```

Important notes:

- I have another project using TwitchLib 1.4.2 on .NET 4.6 that uses identical Username and OAuthToken in order to connect, and it connects just fine with no error.

- Contrary to #156 my issue isn't network or antivirus related, as I am able to run my other project just fine as well.

- I've tested this project using TwitchLib 1.5, 1.4.9 and 1.4.2 to no avail. This error is produced in .NET 4.5.1 and 4.6 (I havent tested other versions).

- Ive also noticed that when I disable the "Prefer 32-bit" option in my project - with all of the other settings set to their defaults - it no longer logs the WebSocketException in the Output view - but it continues to not connect.

**Comment by swiftyspiffy** [comment] 2017-05-29 21:54
Do you get this exception everytime you run run the library? I've seen this error before but it rarely happens. Will look into this further with the latest version. I assume you're running it on win10 VS?

**Comment by phxvyper** [comment] 2017-05-29 21:56
I get this error every instance I run of this project, yes. I'm running Window 10 64-bit with Visual Studio 2017 Professional

**Comment by swiftyspiffy** [comment] 2017-05-30 01:40
Other projects using the same version of the library?

Also, I am unable to reproduce it, but perhaps you can try cloning websocketsharp and debugging/disable this check or simply not throwing an exception:
https://github.com/sta/websocket-sharp/blob/079cd4db39abf65b6d810388a5cd0d61db460142/websocket-sharp/WebSocketFrame.cs#L428

Then try building TwitchLib with that modified websocketsharp library and see if you can get away with simply disabling that check. Other than that, I'm not sure.

**Comment by phxvyper** [comment] 2017-05-30 03:18
@swiftyspiffy disabling that exception further produces the following exception:

```
5/29/2017 20:17:01|Fatal|WebSocket.<startReceiving>b__175_2|System.IndexOutOfRangeException: Index was outside the bounds of the array.
                            at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                            at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                            at WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)
```

Would you be okay with cloning my code and seeing if it runs without that exception?

**Comment by swiftyspiffy** [comment] 2017-05-30 04:16
Yup, I'll try to get back to you about it tomorrow.

**Comment by swiftyspiffy** [comment] 2017-05-31 23:46
This is a total shot in the dark, but I just updated the nuget package to 1.5.1. You might try updating to that see if it resolves anything.

**Comment by swiftyspiffy** [comment] 2017-06-10 22:40
I'm going to go ahead and close this. Feel free to reopen as necessary.

**Closed by swiftyspiffy** 2017-06-10 22:40 UTC

**Comment by phxvyper** [comment] 2017-06-16 20:19
I finally have a chance to get back to this. I uninstall TwitchLib and webshocket-sharp and then reinstalled the latest version of TwitchLib... to no avail:

```cs
6/16/2017 13:12:56|Fatal|WebSocket.<startReceiving>b__175_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                            at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                            at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                            at WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)
```

I added the TwitchLib project to my solution and referenced the project instead of the nuget package. No luck.

.NET version doesnt change anything, as usual.

I even passed my compiled program through my firewall.

Also, the program doesnt crash or anything, its simply that called `Connect();` causes the previously described exception. What do.avi
