### ISSUE TITLE
GetUserFollows only returns 25 results

### ISSUE THREAD

**Issue by drmazo** [swiftyspiffy/TwitchLib#205] opened 2017-05-31 19:06 UTC
Hello,
First of all thanks for the amazing work, this has been working flawlessly for me except for this little issue.

When calling GetUserFollows, it only returns 25 results, despite having a total of 80+ follows.
I tried to change the limit or the offset parameter but to no avail (still 25 same results).
Thanks for your help.

**Comment by swiftyspiffy** [comment] 2017-05-31 19:34
I'm at work at the moment, but I'll try to get this fixed in a few hours, I think I know what the problem is. This and another relatively serious bug should be in a new NuGet version tonight or early tomorrow morning.

Also thanks for the kind words :)

**Comment by drmazo** [comment] 2017-05-31 19:40
No worries, thanks a lot !

**Comment by swiftyspiffy** [comment] 2017-05-31 19:40
If you want to try to fix it locally, the issue is on line 1105 of TwitchLib/Internal/TwitchAPI/v5.cs

The API cal doesn't include the passed in parameters like it should. optionalParameters strings should be appended to the end of the URL.

**Comment by drmazo** [comment] 2017-05-31 19:41
I'll try it

**Comment by drmazo** [comment] 2017-05-31 19:45
Like this ?
`return await Requests.GetGeneric<Models.API.v5.Users.UserFollows>($"https://api.twitch.tv/kraken/users/{userId}/follows/channels" +optionalQuery ,null, Requests.API.v5);`

**Closed** 2017-05-31 23:39 UTC

**Comment by swiftyspiffy** [comment] 2017-05-31 23:45
Fixed.
