### ISSUE TITLE
Chat message not coming

### ISSUE THREAD

**Issue by M0nkeyRage** [swiftyspiffy/TwitchLib#108] opened 2017-01-10 21:32 UTC
I am sure it my issue, any idea why everything seems to connect correctly, but when I connect to chat. I get no messages to my app and if I send messages they either don't show up or only if I refresh the twitch page.

Thanks

**Comment by swiftyspiffy** [comment] 2017-01-13 01:47
Can you try using the Example Application provided in this repo and see if you can see messages from chat in the app? I will need your code to help you.

**Comment by M0nkeyRage** [comment] 2017-01-13 03:02
I tried the example. I got my oauth token from twitchapps.com. It knows my not login is moderator, can send whispers, but nothing from chat. I typed it twitch chat and it did not receive and then sent and it did not go.

Thanks for the help.

On Jan 12, 2017 8:48 PM, Cole <notifications@github.com> wrote:

Can you try using the Example Application provided in this repo and see if you can see messages from chat in the app? I will need your code to help you.

**Comment by swiftyspiffy** [comment] 2017-01-13 09:17
This is very weird. 

This is a site I made that generates a token with all permissions. You are welcome to use it and see if you can use the OAuth token generated by it. It will output it once you authorize. You probably want to revoke access to the app after you've finished testing for security.

https://burkeblack.tv/testapp/twitchauth.php

**Comment by M0nkeyRage** [comment] 2017-01-16 03:49
Ok, finally had time to test it. Same issue. Connects but no chat messages. I used the site you suggested to generate the oauth id.

**Comment by swiftyspiffy** [comment] 2017-01-16 03:57
Can you enable the logger (it's a boolean vallue in the constructor of the client) and dumb the logs here.

**Comment by M0nkeyRage** [comment] 2017-01-17 02:25
I see in the debug that if I step through the SendMessage it tries to write 
":m0nkey_bot!m0nkey_bot@m0nkey_bot.tmi.twitch.tv PRIVMSG #M0nkeyRage :test"
but does not log it. Thanks for all the help.

[TwitchLib] Connecting to: irc.chat.twitch.tv:6667
[TwitchLib] Should be connected!
[TwitchLib] Starting listen..
[TwitchLib] Received: :tmi.twitch.tv 001 m0nkey_bot :Welcome, GLHF!
[TwitchLib] Unaccounted for: :tmi.twitch.tv 001 m0nkey_bot :Welcome, GLHF!
[TwitchLib] Received: :tmi.twitch.tv 002 m0nkey_bot :Your host is tmi.twitch.tv
[TwitchLib] Unaccounted for: :tmi.twitch.tv 002 m0nkey_bot :Your host is tmi.twitch.tv
[TwitchLib] Received: :tmi.twitch.tv 003 m0nkey_bot :This server is rather new
[TwitchLib] Unaccounted for: :tmi.twitch.tv 003 m0nkey_bot :This server is rather new
[TwitchLib] Received: :tmi.twitch.tv 004 m0nkey_bot :-
[TwitchLib] Unaccounted for: :tmi.twitch.tv 004 m0nkey_bot :-
[TwitchLib] Received: :tmi.twitch.tv 375 m0nkey_bot :-
[TwitchLib] Unaccounted for: :tmi.twitch.tv 375 m0nkey_bot :-
[TwitchLib] Received: :tmi.twitch.tv 372 m0nkey_bot :You are in a maze of twisty passages, all alike.
[TwitchLib] Received: :tmi.twitch.tv 376 m0nkey_bot :>
[TwitchLib] Unaccounted for: :tmi.twitch.tv 376 m0nkey_bot :>
[TwitchLib] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
[TwitchLib] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
[TwitchLib] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
[TwitchLib] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
[TwitchLib] Received: :tmi.twitch.tv CAP * ACK :twitch.tv/tags
[TwitchLib] Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags
[TwitchLib] Received: :m0nkey_bot!m0nkey_bot@m0nkey_bot.tmi.twitch.tv JOIN #M0nkeyRage
[TwitchLib] Received: :m0nkey_bot.tmi.twitch.tv 353 m0nkey_bot = #M0nkeyRage :m0nkey_bot
[TwitchLib] Received: :m0nkey_bot.tmi.twitch.tv 366 m0nkey_bot #M0nkeyRage :End of /NAMES list
[TwitchLib] Finished channel joining queue.
[TwitchLib] Unaccounted for: :m0nkey_bot.tmi.twitch.tv 366 m0nkey_bot #M0nkeyRage :End of /NAMES list
[TwitchLib] Received: @badges=moderator/1;color=;display-name=m0nkey_bot;emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #M0nkeyRage
[TwitchLib] Received: @broadcaster-lang=;emote-only=0;followers-only=0;r9k=0;slow=0;subs-only=0 :tmi.twitch.tv ROOMSTATE #M0nkeyRage
The thread 0x2180 has exited with code 0 (0x0).
'TwitchLibExample.exe' (CLR v4.0.30319: TwitchLibExample.exe): Loaded 'C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[TwitchLib] Received: @badges=moderator/1;color=;display-name=m0nkey_bot;emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #m0nkeyrage
[TwitchLib] Unaccounted for: @badges=moderator/1;color=;display-name=m0nkey_bot;emote-sets=0;mod=1;subscriber=0;user-type=mod :tmi.twitch.tv USERSTATE #m0nkeyrage
[TwitchLib] Received: :tmi.twitch.tv PONG tmi.twitch.tv :irc.chat.twitch.tv
The thread 0x18c4 has exited with code 0 (0x0).
[TwitchLib] Received: :tmi.twitch.tv PONG tmi.twitch.tv :irc.chat.twitch.tv
[TwitchLib] Received: PING :tmi.twitch.tv
[TwitchLib] Writing: PONG

**Comment by swiftyspiffy** [comment] 2017-01-17 02:46
It looks like everything worked as expected. ANd you get no new logs if you type something in chat?

**Comment by M0nkeyRage** [comment] 2017-01-17 02:50
No, If I send from the test app or type in twitch chat.

**Comment by swiftyspiffy** [comment] 2017-01-18 21:08
I honestly don't know what to say. It seems to be working for almost everyone. Sorry man :(

**Comment by M0nkeyRage** [comment] 2017-01-18 22:09
No problem. Thanks for checking.  I will try to create another twitch account.  Maybe something there.

On Jan 18, 2017 4:08 PM, Cole <notifications@github.com> wrote:

I honestly don't know what to say. It seems to be working for almost everyone. Sorry man :(

**Comment by M0nkeyRage** [comment] 2017-01-20 03:14
I figured it out. The channel name for the join must be in all lower case otherwise you get no messages. Changed it to lower case and it worked.

**Comment by swiftyspiffy** [comment] 2017-01-20 03:16
Woah, gonna confirm this now. If this is so, this is a serious issue.

Thanks a ton for investigating it.

**Comment by M0nkeyRage** [comment] 2017-01-20 03:17
Please let me know if this turns out to be the case.

**Comment by swiftyspiffy** [comment] 2017-01-20 03:22
Confirmed. Unreal. This is beyond frustrating. Absolutely no reason for shit like this. I'll have the library force channel names to lowercase. Wow.

**Comment by M0nkeyRage** [comment] 2017-01-20 03:22
Thanks for letting me know and for the library. :)

**Comment by swiftyspiffy** [comment] 2017-01-20 03:27
Turns out I had code to prevent this for manually joining channels, but not the auto-join mechanism. Fixing now.

**Comment by swiftyspiffy** [comment] 2017-01-20 03:28
Fixed. b697d6eacc84ba676146424de0aa8bc045a51e16

**Comment by swiftyspiffy** [comment] 2017-01-20 03:29
I'll close this for now, thanks again for bringing this to my attention, and sorry you had to spend over a week on it.

**Closed by swiftyspiffy** 2017-01-20 03:29 UTC
